### ISSUE TITLE
it doesn't work well with recycleview

### ISSUE THREAD

**Issue by Ivolian** [AAkira/ExpandableLayout#19]
![gif](https://cloud.githubusercontent.com/assets/7471905/10759370/d6899b7c-7cf1-11e5-8dd7-399a8478e02e.gif)

As you can see, the first item of recycleview is recycled when i scroll down to the buttom.
So the last item is epanded as the first one.
When i collapse the last one, the first one collapse too.
In fact, they are the same one.
I meet this problem many times and i can't find way to deal with it.
Do you have any idea? Although it's no matter about your library.
Thanks in advance.

**Comment by Ivolian** [comment]
Just call holder.setIsRecyclable(false) to prevent item being recyled.
Recycleview will never recycle.

**Comment by AAkira** [comment]
@Ivolian 
Thank you for your reporting.
I thought this problem is fixed.
I'll report here if I solve it.

**Comment by AAkira** [comment]
@Ivolian 
I fixed it. #20 
You have to set the state of expandable.
For example,  `expandableLayout.setExpanded(boolean)`.
