### ISSUE TITLE
Failed to resolve: com.github.aakira:expandable-layout:1.4.0

### ISSUE THREAD

**Issue by rahulrajeevan** [AAkira/ExpandableLayout#29]
I got above mentioned error when I tried to build after adding this dependency in my build.gradle . 

dependencies {
    compile 'com.github.aakira:expandable-layout:1.4.0@aar'
    
}

**Comment by AAkira** [comment]
@rahulrajeevan 
Do you write this line?

```
buildscript {
    repositories {
        jcenter()
    }
}
```

**Comment by rahulc-nrift** [comment]
@AAkira Yes .

**Comment by rahulrajeevan** [comment]
@AAkira Thanks for quick response . Yes Its already included .

**Comment by AAkira** [comment]
@rahulrajeevan 

Hum...
Please try to use ` compile 'com.github.aakira:expandable-layout:1.3.0@aar'` which is old version.

Or,
Please check your settings.
Preference> Build, > Gradle > Global Gradle Settings > Offline work

**Comment by rahulrajeevan** [comment]
@AAkira Still same error .

**Comment by rahulrajeevan** [comment]
![2015-12-03 08_59_20-nms-app - d__nri-android-projects_nms-android-mobile-coe_nms-app - app - andro](https://cloud.githubusercontent.com/assets/5259427/11551110/371139d4-999c-11e5-8eb6-3c22fd633a9e.png)

**Comment by AAkira** [comment]
@rahulrajeevan 

Do you import another library?
Are there have same error?
Could you check it has same error after creating new project?

I'm sorry I have no idea now.

**Comment by rahulrajeevan** [comment]
@AAkira 
Currently i have following dependencies in my build.gradle 
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.google.android.gms:play-services:7.5.0'
    compile 'org.apache.commons:commons-lang3:3.0'
    compile 'com.ms-square:expandableTextView:0.1.4'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.github.hongyangAndroid:Android-CircleMenu:8a43dbdef9d4325c5717672946904fc9eedf2ab7'
    compile 'com.github.PhilJay:MPAndroidChart:v2.1.3'
    compile 'com.melnykov:floatingactionbutton:1.3.0'
    compile 'com.astuetz:pagerslidingtabstrip:1.0.1'
    compile 'com.amazonaws:aws-android-sdk-core:2.+'
    compile 'com.amazonaws:aws-android-sdk-apigateway-core:2.2.3'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.github.clans:fab:1.6.1'
    compile 'com.shehabic.droppy:Droppy:0.2.5.2@aar'

All those are working fine . But when I include : com.github.aakira:expandable-layout:1.3.0@aar
Above mentioned error occurs .

**Comment by AAkira** [comment]
@rahulrajeevan 

Hmm...
It works on my environment.
I uploaded this to [bintray](https://bintray.com/aakira/maven/expandable-layout).

**Comment by NezSpencer** [comment]
I solved mine by doing this; 
file > project structure > project 
here, I changed my Gradle version from 2.2.1 to 2.4 
when I built again,  all errors cleared.
Hope it helps

**Comment by rahulrajeevan** [comment]
@NezSpencer Thanks a lot for sharing the solution .

**Comment by NezSpencer** [comment]
@rahulrajeevan Has it worked now?

**Comment by rahulrajeevan** [comment]
@NezSpencer Since I didn't find any solution for this ,I have created a custom expandable layout for my purpose . I will try and let you know later .

**Comment by NezSpencer** [comment]
Ok

**Comment by AAkira** [comment]
@NezSpencer 

Thank you for your advice!

**Comment by rahulrajeevan** [comment]
@NezSpencer Your solution worked . Thank you .

**Comment by NezSpencer** [comment]
@AAkira,@rahulrajeevan You are welcome. 
I am guessing this issue should be closed now but then I am new to all this; I dont know the procedures

**Comment by AAkira** [comment]
@NezSpencer @rahulrajeevan 

I'll close this issue if @rahulrajeevan doesn't have others.

**Comment by rahulrajeevan** [comment]
@AAkira Sure . you can close this issue. Thanks a lot for your help and support .

**Comment by AAkira** [comment]
:+1:
