### ISSUE TITLE
RecyclerView item expand or collapse state wrong

### ISSUE THREAD

**Issue by shadowline** [AAkira/ExpandableLayout#3]
when recyclerview item beyond the screen ,expand top item then scroll to the bottom ,the bottom item is also expand
![s50912-120407 1](https://cloud.githubusercontent.com/assets/2800735/9829792/a924f6f0-5946-11e5-95ea-e2aeb83c9482.jpg)
![s50912-120423 1](https://cloud.githubusercontent.com/assets/2800735/9829795/c81d6132-5946-11e5-837c-daaa2f72a488.jpg)

**Comment by AAkira** [comment]
@shadowline 
Thank you for reporting.
I check it.

**Comment by AAkira** [comment]
@shadowline 

I released v1.1.0.
This problem is fixed in this version.
Thanks.
