### ISSUE TITLE
expandrelativelayout wrap_content not work

### ISSUE THREAD

**Issue by Ivolian** [AAkira/ExpandableLayout#31]
ExpandableRelativeLayout is wrap_content, and it hold a LinearLayout as child element.
When LinearLayout's height change, ExpandableRelativeLayout  doesn't change.
I try initLayout, requestLayout, invalidate.
Doesn't work.

**Comment by AAkira** [comment]
@Ivolian 

Thank you for reporting.
Yes,
It is difficult to adjust size if a height of child elements don't be fixed when `onMeasure()` is called.
I'll try to fix this issue.
Please send your PR if you have a good idea. :-)

**Comment by Ivolian** [comment]
![screenshot_2015-12-07-22-26-15](https://cloud.githubusercontent.com/assets/7471905/11629255/060ccc9c-9d32-11e5-9764-30b171a88090.png)

You can see, when I make the first child item VIEW.GONE,
the relativelayout does not work well, it's too high, the red part.

Tonight I use some time to read your code.
I find childPositionList hold the real height of every child item sum.
So why not use it as relativelayout's height or width?

The key code in onMeasure method:
layoutSize = getCurrentPosition();
What about:
layoutSize = getChildPosition(childPositionList.size()-1);

Then, every child item can be VIEW.GONE.
And the example i commented 4 day ago may also be solved.

At last, it's just a idea.

**Comment by AAkira** [comment]
@Ivolian 

I'm so sorry!
I was thinking I fixed this line.
Thank you so much!
I updated this library which is v1.4.1.
Please check it.

**Comment by jemshit** [comment]
wrap_content not working on v1.4.1 @AAkira

**Comment by jemshit** [comment]
i am using ExpandableRelativeLayout

**Comment by jemshit** [comment]
there is a huge space at bottom of layout

**Comment by jemshit** [comment]
OK, it worked after i added RelativeLayout inside ExpandableRelativeLayout(wrap_content). All other views are inside RelativeLayout(wrap_content)

**Comment by zaheerahmad** [comment]
@AAkira First of all nice library :+1: 

It seems like 'wrap_content' in ExpandableRelativeLayout is not working in 1.4.3. I downgraded it to 1.4.1 and its all working fine.

**Comment by AAkira** [comment]
@jemshit  @zaheerahmad 

I'm sorry that I didn't notice.
I fixed it in v1.5.0.
Please check it.
