### ISSUE TITLE
Application Crash on recreate While don't keep activity in background is checked

### ISSUE THREAD

**Issue by tahirawan4** [AAkira/ExpandableLayout#34]
Its a strange behaviour, when ever activity goes in background and we try to recreate it, it crashes with following error Unmarshalling unknown type code 37 at offset 724.
After removing ExpandableRelativelayout it works ok.

**Comment by AAkira** [comment]
@tahirawan4 

Hmm...
I'm sorry I have no idea solving this problem.
I am suspicious of `parcerable`.
Do you do anything in `onPause()` or `onResume()`?

**Comment by tahirawan4** [comment]
Problem was in your code. You put size in parcable in expandablestate but not weight and try to read both.  Fix it

**Comment by AAkira** [comment]
@tahirawan4 

I see.
@Desdroid fixed this problem.
I'll release next version.

But I don't check it yet.
Don't close this issue if I comment here. :-D

**Comment by suren123** [comment]
In ExpandableSavedState.java

    public void writeToParcel(Parcel out, int flags) {
        super.writeToParcel(out, flags);
        out.writeInt(this.size);
        **out.writeFloat(this.weight);**
    }

will fix this bug

**Comment by AAkira** [comment]
@tahirawan4 @suren123 

I'm sorry for fixing this issue is late.
I upload the next version (v1.4.2).
Please check it.
