### ISSUE TITLE
[BUG] Layout Size measurement

### ISSUE THREAD

**Issue by Desdroid** [AAkira/ExpandableLayout#35]
First of all thanks for this nice libary and all the efford you put into it. :+1: 
#### Issue

I discovered an Issue with the measurement of the Layout size, when you put different childviews next to each other (with `<android:layout_toRightOf="@id/someId"> `)
It will measure the height as if all child views would be placed below from each other.
See example Layout
```xml
<de.desdroid.zauberkueche.ExpandableRelativeLayout
        android:id="@+id/expand_image"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:ael_duration="500"
        app:ael_expanded="false"
        app:ael_interpolator="decelerate"
        app:ael_orientation="vertical">
            <ImageView
                android:id="@+id/img_food"
                android:layout_width="@dimen/img_width_food"
                android:layout_height="@dimen/img_height_food"
                android:scaleType="fitCenter"
                android:src="@drawable/ic_cake" />

            <Button
                android:id="@+id/btn_gallery"
                style="@style/Widget.AppCompat.Button.Borderless"
                android:layout_width="@dimen/btn_width_add_photo"
                android:layout_height="@dimen/btn_height_add_photo"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
                android:layout_marginEnd="@dimen/padding_48dp"
                android:layout_marginLeft="@dimen/padding_8dp"
                android:layout_marginRight="@dimen/padding_48dp"
                android:layout_marginStart="@dimen/padding_8dp"
                android:drawablePadding="@dimen/padding_8dp"
                android:drawableTop="@drawable/ic_cake"
                android:text="@string/btn_gallery" />

            <Button
                android:id="@+id/btn_photo"
                style="@style/Widget.AppCompat.Button.Borderless"
                android:layout_width="@dimen/btn_width_add_photo"
                android:layout_height="@dimen/btn_height_add_photo"
                android:layout_marginLeft="@dimen/padding_8dp"
                android:layout_marginRight="@dimen/padding_8dp"
                android:layout_toLeftOf="@id/btn_gallery"
                android:layout_toStartOf="@id/btn_gallery"
                android:drawablePadding="@dimen/padding_8dp"
                android:drawableTop="@drawable/ic_cake"
                android:text="@string/btn_photo" />  

</de.desdroid.zauberkueche.ExpandableRelativeLayout>  

```

#### Possible fix
I don't understand why you calculate the layout height on your own.
In your code of ExpandableRelativeLayout you call 
```java
  super.onMeasure(widthMeasureSpec, heightMeasureSpec);
```
So your parent class, which is RelativeLayout will already calculate height and width of the Layout.
You could then simply get Height and Width by 
```java
  super.getMeasuredHeight();
  // Or respectively for horizontal orientation
  super.getMeasuredWidth();
```
When I set your local attribute layoutSize with the value retained by the super method, the bug is fixed.

### Workaround
Until this Bug is fixed, users can alternatively wrap their childs into one RelativeLayout and set it as the only child of ExpandableRelativeLayout.

### Conclusion
I propose deleting the whole calculation block and using the super methods, for setting the layoutsize.
*Or is there any reason why you have to calculate it on your own ? If so, please explain :)*

**Comment by Desdroid** [comment]
If you want to use the proposed fix, I would be happy to provide a PR.

**Comment by AAkira** [comment]
@Desdroid 

Thank you for a polite reporting. :+1: 

I know this method which is `getMeasuredHeight()` and `getMeasuredWidth()`.
But these don't work as I expect to.

* your question  

> Or is there any reason why you have to calculate it on your own ?

I want to create `ExpandableRelativeLayout.move()` and `ExpandableRelativeLayout.moveChild()`.
So, I calculate the height and width in `onMeasure()`.

And my library seems to work.
I pushed the test branch.
Is this correct code implemented your explaining?
Please check it if my code is wrong.
https://github.com/AAkira/ExpandableLayout/compare/feature/test?expand=1

**Comment by Desdroid** [comment]
@AAkira 
You're welcome, nothing is more annoying than a bad bug report.
Ahh, now i see why they are necessary.

Acutally I think now that my "Bug"  might be some misunderstanding in the usage of the libary.
As reported (I used some wrong Markdown now it's visible) I was putting inside your Layout 3 Child views, which were aligned next to each other. (`android:layout_toRightOf="@id/someId"`)
The orientation of the `ExpandableRelativeLayout` was __vertical__. 

In your logic those 3 elements were 3 different children and since orientation was vertical you wanted to provide me the ability to move them (upwards or downwards).
Therefore you calculated the layout as if they were all beneath each other and when I did expand it, it had a height, which was tooo high.

For me though, these 3 childs were logically 1 Child (1 row). I didn't want them to move. I guess for my use case you really have to put those 3 children into 1 Layout.

__Nevertheless I'm gonna show you my use case in the test branch, I currently don't have that much time, hope I'll be able to do it tomorrow.__

Some possible options which come to my mind:
   * Check in your calculation also the alignment and take it into account (along with the height calculated by the RelativeLayout)   
or :  

   * Make in your Readme the concept more clear (Everything which is for the user one logic row has to be put inside a layout)

**Comment by Desdroid** [comment]
I opened a PR, you can have a look at it.

Here are some screenshots to the issue.
This is the layout colaapsed, the pink view is some other content beneath.
![screen collapsed](https://cloud.githubusercontent.com/assets/13335576/11858161/529741bc-a45f-11e5-9cf1-1ce95a928dab.png)

This is the layout expanded, as you can see the white space is wrong here.
It has exactly the size of the blue text view.

![screen_expanded](https://cloud.githubusercontent.com/assets/13335576/11858182/78a02bda-a45f-11e5-9554-161f77d75a9c.png)

And finally here is the Log to the "wrong" height calculation.
![wrong height calculation](https://cloud.githubusercontent.com/assets/13335576/11858186/87e7f262-a45f-11e5-8862-f53a9221ea5c.png)


__As already stated I think it's not really a "bug" but rather a case where you have to take special steps (Wrap the views for a logic row in one layout --> Then it will be 1 child for your layout as well)__
