### ISSUE TITLE
setExpand(boolean) is not working right in RecyclerView

### ISSUE THREAD

**Issue by andyxialm** [AAkira/ExpandableLayout#57]
When I scroll a RecyclerView, and use the method 'setExpand(boolean)' in onBindViewHolder(). 
The expand or collapse state isn't right.
PS: All boolean data in a SparseBooleanArray,  datas are correct.  And it isn't a convert question.

**Comment by AAkira** [comment]
I fixed this problem.
I will also release the next version soon.
