### ISSUE TITLE
ExpandableLayout with LinearLayout

### ISSUE THREAD

**Issue by lukachuuu** [AAkira/ExpandableLayout#58]
Hello everyone,

I have small problem with expandable relative layout. In my layout I using linear layout inside expandable relative layout and I programmatically add textview on this linear layout. This method work ok in onCreate() method but when i waiting data from server and after receiving data i trying add view to linear layout inside expandable layout, nothing happens. Does anyone know where is the problem?

Code is below:

` <com.github.aakira.expandablelayout.ExpandableRelativeLayout
                            android:id="@+id/expandableLayout"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            app:ael_expanded="false"
                            app:ael_duration="300"
                            app:ael_interpolator="fastOutLinearIn"
                            app:ael_orientation="vertical">

                        <LinearLayout
                                android:layout_width="match_parent"
                                android:layout_height="match_parent"
                                android:id="@+id/fee_container"
                                android:orientation="vertical"
                                />

</com.github.aakira.expandablelayout.ExpandableRelativeLayout>`

and java code:

` for (int i = 0; i < 3; i++) {

            View layout = LayoutInflater.from(getApplicationContext())
                    .inflate(R.layout.fee_item, mFeeContainer, false);

            TextView mPrice = (TextView) layout.findViewById(R.id.price);
            TextView mType = (TextView) layout.findViewById(R.id.type);

            mPrice.setText("price" + i);
            mType.setText("type" + i);

            mFeeContainer.addView(layout);
        }`

**Comment by lukachuuu** [comment]
@AAkira I trying your expandable linear layout and works fine with dynamic data. When are you going to merge 1.5 branch into master? Thanks

**Comment by AAkira** [comment]
@lukachuuu 

I don't have solved issues yet.
I release it as a snapshot if you need.

**Comment by AAkira** [comment]
@lukachuuu 

I released v1.5.0 just now.
Please check it.

**Comment by lukachuuu** [comment]
Expandable linear layout works fine right now, thanks a lot :+1:
