### ISSUE TITLE
Fix initLayout

### ISSUE THREAD

**Issue by AAkira** [AAkira/ExpandableLayout#66]
You should use the ExpandableLinearLayout if child views may change a size. 
For example, it gets and sets values after connection.
The ExpandableRelativeLayout isn't supported in the above.

```java
child.setText("Sets text from a server");
expandableLayout.initLayout(true);``// Recalculate size of children
```

`initLayout()` is deprecated in v1.5.0.
The argument of `isMaintain`  doesn't work.

**Comment by DuShunpeng** [comment]
looks like it is don't work to the initLayout by the child and expandableLinearLayout in item of recycle view when you reset the text to the child which is a textview.
Could you pls double check the issue. thanks!

**Comment by DuShunpeng** [comment]
looks like there some issues when you set different text in textview which in recycler view holder.
the height of expandable layout will changed by scroll the recycle view.
could you pls double check the issue figure out what's going on,thanks
1.set different lines of string in textview which in recycle view holder.
2.scroll the recycle view by and check the textview's height 

thanks a lot
