### ISSUE TITLE
Issue with isExpanded

### ISSUE THREAD

**Issue by Jawnnypoo** [AAkira/ExpandableLayout#68]
Both ExpandableLinearLayout and ExpandableRelativeLayout are incorrectly reporting their isExpanded() state after you expand, collapse and expand again. The layout always reports that it is expanded.

**Comment by Jawnnypoo** [comment]
This is something that was introduced with 1.5.0. Reverting back to 1.4.3 removes the issue.

**Comment by AAkira** [comment]
@Jawnnypoo 

Thank you for reporting.

The cause of this issue is the layout is calculated asynchronous on requestLayout.
Fix it #69 and release v1.5.1.

**Comment by Jawnnypoo** [comment]
Nice quick fix! Thanks!
